import React, { useEffect, useState, createContext, useContext } from 'react';
type Language = 'en' | 'ar';
interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}
const translations = {
  en: {
    welcome: 'Welcome',
    login: 'Sign In',
    email: 'Email',
    password: 'Password',
    rememberMe: 'Remember Me',
    biometricLogin: 'Sign in with Biometric',
    dashboard: 'Dashboard',
    workOrders: 'Work Orders',
    assets: 'Devices',
    spareParts: 'Spare Parts',
    reports: 'Reports',
    notifications: 'Notifications',
    settings: 'Settings',
    logout: 'Logout',
    activeWOs: 'Active',
    overdue: 'Overdue',
    completedToday: 'Completed Today',
    ppmDue: 'PPM Due',
    viewAll: 'View All',
    newWorkOrder: 'New Work Order',
    scanAsset: 'Scan Device',
    workOrderDetails: 'Work Order Details',
    assetProfile: 'Device Profile',
    maintenanceHistory: 'Maintenance History',
    completeWorkOrder: 'Complete Work Order',
    addStep: 'Add Step',
    uploadPhoto: 'Upload Photo',
    signature: 'Digital Signature',
    signHere: 'Sign Here',
    clear: 'Clear',
    save: 'Save',
    cancel: 'Cancel',
    issue: 'Issue',
    return: 'Return',
    search: 'Search',
    filter: 'Filter',
    export: 'Export',
    markAllRead: 'Mark All as Read',
    noData: 'No data available',
    loading: 'Loading...',
    error: 'Unable to load data',
    retry: 'Tap to retry',
    // Settings Page
    managePreferences: 'Manage your preferences',
    accountSettings: 'Account Settings',
    security: 'Security',
    appInformation: 'App Information',
    // Account Settings
    changeLanguage: 'Change Language',
    currentLanguage: 'English',
    changePassword: 'Change Password',
    updatePassword: 'Update your password',
    changeMobileNumber: 'Change Mobile Number',
    changeEmail: 'Change Email',
    userSignature: 'User Signature',
    manageSignature: 'Manage your signature',
    signatureSet: 'Signature set',
    noSignature: 'No signature',
    // Security
    biometricAuthentication: 'Biometric Authentication',
    enabled: 'Enabled',
    disabled: 'Disabled',
    // App Info
    aboutApp: 'About the App',
    learnMore: 'Learn more about BIOMARK',
    appVersion: 'App Version',
    siteInformation: 'Site Information',
    viewSiteDetails: 'View site details',
    // Language Modal
    selectLanguage: 'Select Language',
    english: 'English',
    englishUS: 'English (US)',
    arabic: 'Arabic',
    arabicSA: 'Arabic (Saudi Arabia)',
    // Password Modal
    currentPassword: 'Current Password',
    enterCurrentPassword: 'Enter current password',
    newPassword: 'New Password',
    enterNewPassword: 'Enter new password',
    confirmNewPassword: 'Confirm New Password',
    confirmPassword: 'Confirm new password',
    updatePasswordBtn: 'Update Password',
    // Mobile Modal
    mobileNumber: 'Mobile Number',
    mobileNumberPlaceholder: '+966 50 123 4567',
    verificationCodeSent: 'A verification code will be sent to your new mobile number',
    updateNumber: 'Update Number',
    // Email Modal
    emailAddress: 'Email Address',
    emailPlaceholder: 'ahmed@hospital.com',
    verificationLinkSent: 'A verification link will be sent to your new email address',
    updateEmail: 'Update Email',
    // About Modal
    aboutBiomark: 'About BIOMARK',
    biomarkCMMS: 'BIOMARK CMMS',
    healthcareMaintenance: 'Healthcare Maintenance Management',
    version: 'Version',
    developer: 'Developer',
    biomarkTech: 'BIOMARK Technologies',
    support: 'Support',
    supportEmail: 'support@biomark.com',
    close: 'Close',
    allRightsReserved: '© 2024 BIOMARK. All rights reserved.',
    healthcareCMMS: 'Healthcare CMMS Platform',
    // Site Information Modal
    facilityName: 'Facility Name',
    country: 'Country',
    activeUntil: 'Active Until',
    teamMembers: 'Team Members',
    kuwait: 'Kuwait',
    alSeefHospital: 'Al Seef Hospital',
    members: 'Members',
    active: 'Active',
    inactive: 'Inactive',
    status: 'Status',
    // Signature Modal
    drawSignature: 'Draw Your Signature',
    signatureInstructions: 'Draw your signature in the box below',
    clearSignature: 'Clear',
    saveSignature: 'Save Signature',
    signatureSaved: 'Signature saved successfully',
    // Filter Modal
    filterAssets: 'Filter Devices',
    location: 'Location',
    manufacturer: 'Manufacturer',
    riskFactor: 'Risk Factor',
    assetType: 'Device Type',
    allLocations: 'All Locations',
    allManufacturers: 'All Manufacturers',
    allRiskFactors: 'All Risk Factors',
    allAssetTypes: 'All Device Types',
    highRisk: 'High Risk',
    mediumRisk: 'Medium Risk',
    lowRisk: 'Low Risk',
    applyFilters: 'Apply Filters',
    clearFilters: 'Clear Filters',
    icu: 'ICU',
    emergency: 'Emergency',
    operatingRoom: 'Operating Room',
    generalWard: 'General Ward',
    ventilator: 'Ventilator',
    monitor: 'Monitor',
    infusionPump: 'Infusion Pump',
    xrayMachine: 'X-Ray Machine',
    // Maintenance Types
    preventive: 'Preventive',
    corrective: 'Corrective',
    calibration: 'Calibration',
    // Maintenance Details
    maintenanceDetails: 'Maintenance Details',
    maintenanceType: 'Maintenance Type',
    technician: 'Technician',
    date: 'Date',
    duration: 'Duration',
    description: 'Description',
    minutes: 'minutes',
    partsUsed: 'Parts Used',
    laborCost: 'Labor Cost',
    partsCost: 'Parts Cost',
    totalCost: 'Total Cost',
    notes: 'Notes',
    completedBy: 'Completed By',
    // Duty Status
    dutyStatus: 'Duty Status',
    onDuty: 'On Duty',
    offDuty: 'Off Duty',
    youAreCurrently: 'You are currently',
    // Warranty Status
    warrantyStatus: 'Warranty Status',
    expiringWarranties: 'Expiring Warranties',
    expiredWarranties: 'Expired Warranties',
    expiringIn30Days: 'Expiring in 30 days',
    expiredPast14Days: 'Expired in past 14 days',
    assetsExpiringSoon: 'devices expiring soon',
    assetsExpired: 'devices expired',
    reviewWarranties: 'Review and take action before expiration',
    // Recently Installed Devices
    recentlyInstalled: 'Recently Installed',
    newAssetsAdded: 'New Devices Added',
    installedLast14Days: 'Installed in last 14 days',
    newAssets: 'new devices',
    viewNewAssets: 'View all recently installed devices',
    installedOn: 'Installed on',
    // NFC Scanner
    scanningAsset: 'Scanning Device',
    holdPhoneNearTag: 'Hold your phone near the NFC tag',
    scanningInProgress: 'Scanning in progress...',
    movePhoneCloser: 'Move phone closer to tag',
    nfcNotSupported: 'NFC not supported on this device',
    enableNFC: 'Please enable NFC in your device settings',
    scanSuccess: 'Scan successful!',
    scanFailed: 'Scan failed. Please try again.',
    // Export & Share
    exportReport: 'Export Report',
    shareReport: 'Share Report',
    exportAsPDF: 'Export as PDF',
    sendByEmail: 'Send by Email',
    downloadPDF: 'Download PDF',
    emailReport: 'Email Report',
    enterEmailAddress: 'Enter email address',
    sendReport: 'Send Report',
    reportGenerated: 'Report generated successfully',
    reportSent: 'Report sent successfully',
    generatingReport: 'Generating report...',
    sendingEmail: 'Sending email...',
    deviceReport: 'Device Report',
    // IPM Section
    ipm: 'IPM',
    inspection: 'Inspection',
    preventiveMaintenance: 'Preventive Maintenance',
    inspectionAndPM: 'Inspection & Preventive Maintenance',
    assignedInspections: 'Assigned Inspections',
    assignedPM: 'Assigned PM',
    noInspectionsAssigned: 'No inspections assigned',
    noPMAssigned: 'No preventive maintenance assigned',
    inspectionTasks: 'inspection tasks',
    pmTasks: 'PM tasks',
    viewInspections: 'View Inspections',
    viewPM: 'View PM Tasks',
    dueToday: 'Due Today',
    dueSoon: 'Due Soon',
    taskNumber: 'Task Number',
    startDate: 'Start Date',
    dueDate: 'Due Date',
    inspections: 'Inspections',
    assignedTasks: 'Assigned Tasks',
    tasksAssigned: 'tasks assigned',
    overdueTask: 'Overdue',
    machineName: 'Machine Name',
    machineCode: 'Machine Code',
    deviceName: 'Device Name',
    deviceCode: 'Device Code',
    // Inspection Details
    inspectionDetails: 'Inspection Details',
    jobDetails: 'Job Details',
    equipment: 'Equipment',
    equipmentList: 'Equipment List',
    jobDescription: 'Job Description',
    priority: 'Priority',
    assignedTo: 'Assigned To',
    createdDate: 'Created Date',
    estimatedDuration: 'Estimated Duration',
    jobStatus: 'Job Status',
    equipmentCount: 'Equipment Count',
    viewEquipment: 'View Equipment',
    noEquipment: 'No equipment assigned',
    serialNumber: 'Serial Number',
    model: 'Model',
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
    pending: 'Pending',
    inProgress: 'In Progress',
    completed: 'Completed',
    hours: 'hours',
    items: 'items',
    startInspection: 'Start Inspection',
    completeInspection: 'Complete Inspection',
    // Equipment Inspection
    equipmentInspection: 'Equipment Inspection',
    deviceDetails: 'Device Details',
    inspectionSteps: 'Inspection Steps',
    attachImages: 'Attach Images',
    addPhoto: 'Add Photo',
    takePhoto: 'Take Photo',
    chooseFromGallery: 'Choose from Gallery',
    removePhoto: 'Remove Photo',
    saveAndNext: 'Save & Next',
    saveInspection: 'Save Inspection',
    inspectionSaved: 'Inspection saved successfully!',
    movingToNext: 'Moving to next device...',
    allDevicesCompleted: 'All devices inspected!',
    returnToList: 'Return to List',
    step: 'Step',
    pass: 'Pass',
    fail: 'Fail',
    notApplicable: 'N/A',
    photos: 'photos',
    photoAttached: 'photo attached',
    photosAttached: 'photos attached',
    noPhotos: 'No photos attached',
    deviceInfo: 'Device Information',
    inspectionProgress: 'Inspection Progress',
    of: 'of',
    nextDevice: 'Next Device',
    previousDevice: 'Previous Device',
    // PM Checklist
    pmChecklist: 'PM Checklist',
    maintenanceChecklist: 'Maintenance Checklist',
    pmDetails: 'PM Details',
    savePM: 'Save PM',
    pmSaved: 'PM saved successfully!',
    completePM: 'Complete PM'
  },
  ar: {
    welcome: 'مرحباً',
    login: 'تسجيل الدخول',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    rememberMe: 'تذكرني',
    biometricLogin: 'تسجيل الدخول بالبصمة',
    dashboard: 'لوحة التحكم',
    workOrders: 'أوامر العمل',
    assets: 'الأجهزة',
    spareParts: 'قطع الغيار',
    reports: 'التقارير',
    notifications: 'الإشعارات',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    activeWOs: 'نشط',
    overdue: 'متأخر',
    completedToday: 'مكتمل اليوم',
    ppmDue: 'صيانة مستحقة',
    viewAll: 'عرض الكل',
    newWorkOrder: 'أمر عمل جديد',
    scanAsset: 'مسح الجهاز',
    workOrderDetails: 'تفاصيل أمر العمل',
    assetProfile: 'ملف الجهاز',
    maintenanceHistory: 'سجل الصيانة',
    completeWorkOrder: 'إكمال أمر العمل',
    addStep: 'إضافة خطوة',
    uploadPhoto: 'تحميل صورة',
    signature: 'التوقيع الرقمي',
    signHere: 'وقع هنا',
    clear: 'مسح',
    save: 'حفظ',
    cancel: 'إلغاء',
    issue: 'إصدار',
    return: 'إرجاع',
    search: 'بحث',
    filter: 'تصفية',
    export: 'تصدير',
    markAllRead: 'تعليم الكل كمقروء',
    noData: 'لا توجد بيانات',
    loading: 'جاري التحميل...',
    error: 'تعذر تحميل البيانات',
    retry: 'اضغط للمحاولة مرة أخرى',
    // Settings Page
    managePreferences: 'إدارة التفضيلات الخاصة بك',
    accountSettings: 'إعدادات الحساب',
    security: 'الأمان',
    appInformation: 'معلومات التطبيق',
    // Account Settings
    changeLanguage: 'تغيير اللغة',
    currentLanguage: 'العربية',
    changePassword: 'تغيير كلمة المرور',
    updatePassword: 'تحديث كلمة المرور الخاصة بك',
    changeMobileNumber: 'تغيير رقم الجوال',
    changeEmail: 'تغيير البريد الإلكتروني',
    userSignature: 'توقيع المستخدم',
    manageSignature: 'إدارة التوقيع الخاص بك',
    signatureSet: 'تم تعيين التوقيع',
    noSignature: 'لا يوجد توقيع',
    // Security
    biometricAuthentication: 'المصادقة البيومترية',
    enabled: 'مفعّل',
    disabled: 'معطّل',
    // App Info
    aboutApp: 'حول التطبيق',
    learnMore: 'تعرف على المزيد حول BIOMARK',
    appVersion: 'إصدار التطبيق',
    siteInformation: 'معلومات الموقع',
    viewSiteDetails: 'عرض تفاصيل الموقع',
    // Language Modal
    selectLanguage: 'اختر اللغة',
    english: 'الإنجليزية',
    englishUS: 'الإنجليزية (الولايات المتحدة)',
    arabic: 'العربية',
    arabicSA: 'العربية (المملكة العربية السعودية)',
    // Password Modal
    currentPassword: 'كلمة المرور الحالية',
    enterCurrentPassword: 'أدخل كلمة المرور الحالية',
    newPassword: 'كلمة المرور الجديدة',
    enterNewPassword: 'أدخل كلمة المرور الجديدة',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
    confirmPassword: 'تأكيد كلمة المرور الجديدة',
    updatePasswordBtn: 'تحديث كلمة المرور',
    // Mobile Modal
    mobileNumber: 'رقم الجوال',
    mobileNumberPlaceholder: '٠٥٠ ١٢٣ ٤٥٦٧ ٩٦٦+',
    verificationCodeSent: 'سيتم إرسال رمز التحقق إلى رقم الجوال الجديد',
    updateNumber: 'تحديث الرقم',
    // Email Modal
    emailAddress: 'عنوان البريد الإلكتروني',
    emailPlaceholder: 'ahmed@hospital.com',
    verificationLinkSent: 'سيتم إرسال رابط التحقق إلى البريد الإلكتروني الجديد',
    updateEmail: 'تحديث البريد الإلكتروني',
    // About Modal
    aboutBiomark: 'حول BIOMARK',
    biomarkCMMS: 'نظام BIOMARK للصيانة',
    healthcareMaintenance: 'إدارة صيانة الرعاية الصحية',
    version: 'الإصدار',
    developer: 'المطور',
    biomarkTech: 'BIOMARK Technologies',
    support: 'الدعم الفني',
    supportEmail: 'support@biomark.com',
    close: 'إغلاق',
    allRightsReserved: '© ٢٠٢٤ BIOMARK. جميع الحقوق محفوظة.',
    healthcareCMMS: 'منصة إدارة صيانة الرعاية الصحية',
    // Site Information Modal
    facilityName: 'اسم المنشأة',
    country: 'الدولة',
    activeUntil: 'نشط حتى',
    teamMembers: 'أعضاء الفريق',
    kuwait: 'الكويت',
    alSeefHospital: 'مستشفى السيف',
    members: 'عضو',
    active: 'نشط',
    inactive: 'غير نشط',
    status: 'الحالة',
    // Signature Modal
    drawSignature: 'ارسم توقيعك',
    signatureInstructions: 'ارسم توقيعك في المربع أدناه',
    clearSignature: 'مسح',
    saveSignature: 'حفظ التوقيع',
    signatureSaved: 'تم حفظ التوقيع بنجاح',
    // Filter Modal
    filterAssets: 'تصفية الأجهزة',
    location: 'الموقع',
    manufacturer: 'الشركة المصنعة',
    riskFactor: 'عامل الخطر',
    assetType: 'نوع الجهاز',
    allLocations: 'جميع المواقع',
    allManufacturers: 'جميع الشركات المصنعة',
    allRiskFactors: 'جميع عوامل الخطر',
    allAssetTypes: 'جميع أنواع الأجهزة',
    highRisk: 'خطر عالي',
    mediumRisk: 'خطر متوسط',
    lowRisk: 'خطر منخفض',
    applyFilters: 'تطبيق التصفية',
    clearFilters: 'مسح التصفية',
    icu: 'العناية المركزة',
    emergency: 'الطوارئ',
    operatingRoom: 'غرفة العمليات',
    generalWard: 'الجناح العام',
    ventilator: 'جهاز التنفس',
    monitor: 'جهاز المراقبة',
    infusionPump: 'مضخة التسريب',
    xrayMachine: 'جهاز الأشعة السينية',
    // Maintenance Types
    preventive: 'وقائية',
    corrective: 'تصحيحية',
    calibration: 'معايرة',
    // Maintenance Details
    maintenanceDetails: 'تفاصيل الصيانة',
    maintenanceType: 'نوع الصيانة',
    technician: 'الفني',
    date: 'التاريخ',
    duration: 'المدة',
    description: 'الوصف',
    minutes: 'دقيقة',
    partsUsed: 'القطع المستخدمة',
    laborCost: 'تكلفة العمالة',
    partsCost: 'تكلفة القطع',
    totalCost: 'التكلفة الإجمالية',
    notes: 'ملاحظات',
    completedBy: 'أكمله',
    // Duty Status
    dutyStatus: 'حالة الخدمة',
    onDuty: 'في الخدمة',
    offDuty: 'خارج الخدمة',
    youAreCurrently: 'أنت حالياً',
    // Warranty Status
    warrantyStatus: 'حالة الضمان',
    expiringWarranties: 'ضمانات منتهية قريباً',
    expiredWarranties: 'ضمانات منتهية',
    expiringIn30Days: 'تنتهي خلال ٣٠ يوم',
    expiredPast14Days: 'انتهت خلال ١٤ يوم الماضية',
    assetsExpiringSoon: 'أجهزة تنتهي قريباً',
    assetsExpired: 'أجهزة منتهية',
    reviewWarranties: 'راجع واتخذ إجراء قبل الانتهاء',
    // Recently Installed Devices
    recentlyInstalled: 'المثبتة حديثاً',
    newAssetsAdded: 'أجهزة جديدة مضافة',
    installedLast14Days: 'تم تثبيتها خلال ١٤ يوم الماضية',
    newAssets: 'أجهزة جديدة',
    viewNewAssets: 'عرض جميع الأجهزة المثبتة حديثاً',
    installedOn: 'تم التثبيت في',
    // NFC Scanner
    scanningAsset: 'مسح الجهاز',
    holdPhoneNearTag: 'ضع هاتفك بالقرب من علامة NFC',
    scanningInProgress: 'جاري المسح...',
    movePhoneCloser: 'قرّب الهاتف من العلامة',
    nfcNotSupported: 'NFC غير مدعوم على هذا الجهاز',
    enableNFC: 'يرجى تفعيل NFC في إعدادات جهازك',
    scanSuccess: 'تم المسح بنجاح!',
    scanFailed: 'فشل المسح. يرجى المحاولة مرة أخرى.',
    // Export & Share
    exportReport: 'تصدير التقرير',
    shareReport: 'مشاركة التقرير',
    exportAsPDF: 'تصدير كـ PDF',
    sendByEmail: 'إرسال بالبريد',
    downloadPDF: 'تحميل PDF',
    emailReport: 'إرسال التقرير بالبريد',
    enterEmailAddress: 'أدخل عنوان البريد الإلكتروني',
    sendReport: 'إرسال التقرير',
    reportGenerated: 'تم إنشاء التقرير بنجاح',
    reportSent: 'تم إرسال التقرير بنجاح',
    generatingReport: 'جاري إنشاء التقرير...',
    sendingEmail: 'جاري إرسال البريد...',
    deviceReport: 'تقرير الجهاز',
    // IPM Section
    ipm: 'الفحص والصيانة الوقائية',
    inspection: 'الفحص',
    preventiveMaintenance: 'الصيانة الوقائية',
    inspectionAndPM: 'الفحص والصيانة الوقائية',
    assignedInspections: 'الفحوصات المعينة',
    assignedPM: 'الصيانة الوقائية المعينة',
    noInspectionsAssigned: 'لا توجد فحوصات معينة',
    noPMAssigned: 'لا توجد صيانة وقائية معينة',
    inspectionTasks: 'مهام الفحص',
    pmTasks: 'مهام الصيانة الوقائية',
    viewInspections: 'عرض الفحوصات',
    viewPM: 'عرض مهام الصيانة',
    dueToday: 'مستحق اليوم',
    dueSoon: 'مستحق قريباً',
    taskNumber: 'رقم المهمة',
    startDate: 'تاريخ البدء',
    dueDate: 'تاريخ الاستحقاق',
    inspections: 'الفحوصات',
    assignedTasks: 'المهام المعينة',
    tasksAssigned: 'مهام معينة',
    overdueTask: 'متأخر',
    machineName: 'اسم الجهاز',
    machineCode: 'رمز الجهاز',
    deviceName: 'اسم الجهاز',
    deviceCode: 'رمز الجهاز',
    // Inspection Details
    inspectionDetails: 'تفاصيل الفحص',
    jobDetails: 'تفاصيل المهمة',
    equipment: 'المعدات',
    equipmentList: 'قائمة المعدات',
    jobDescription: 'وصف المهمة',
    priority: 'الأولوية',
    assignedTo: 'معين لـ',
    createdDate: 'تاريخ الإنشاء',
    estimatedDuration: 'المدة المقدرة',
    jobStatus: 'حالة المهمة',
    equipmentCount: 'عدد المعدات',
    viewEquipment: 'عرض المعدات',
    noEquipment: 'لا توجد معدات معينة',
    serialNumber: 'الرقم التسلسلي',
    model: 'الموديل',
    critical: 'حرج',
    high: 'عالي',
    medium: 'متوسط',
    low: 'منخفض',
    pending: 'قيد الانتظار',
    inProgress: 'قيد التنفيذ',
    completed: 'مكتمل',
    hours: 'ساعات',
    items: 'عناصر',
    startInspection: 'بدء الفحص',
    completeInspection: 'إكمال الفحص',
    // Equipment Inspection
    equipmentInspection: 'فحص المعدات',
    deviceDetails: 'تفاصيل الجهاز',
    inspectionSteps: 'خطوات الفحص',
    attachImages: 'إرفاق صور',
    addPhoto: 'إضافة صورة',
    takePhoto: 'التقاط صورة',
    chooseFromGallery: 'اختيار من المعرض',
    removePhoto: 'إزالة الصورة',
    saveAndNext: 'حفظ والتالي',
    saveInspection: 'حفظ الفحص',
    inspectionSaved: 'تم حفظ الفحص بنجاح!',
    movingToNext: 'الانتقال إلى الجهاز التالي...',
    allDevicesCompleted: 'تم فحص جميع الأجهزة!',
    returnToList: 'العودة إلى القائمة',
    step: 'خطوة',
    pass: 'نجح',
    fail: 'فشل',
    notApplicable: 'غير قابل للتطبيق',
    photos: 'صور',
    photoAttached: 'صورة مرفقة',
    photosAttached: 'صور مرفقة',
    noPhotos: 'لا توجد صور مرفقة',
    deviceInfo: 'معلومات الجهاز',
    inspectionProgress: 'تقدم الفحص',
    of: 'من',
    nextDevice: 'الجهاز التالي',
    previousDevice: 'الجهاز السابق',
    // PM Checklist
    pmChecklist: 'قائمة الصيانة الوقائية',
    maintenanceChecklist: 'قائمة الصيانة',
    pmDetails: 'تفاصيل الصيانة الوقائية',
    savePM: 'حفظ الصيانة الوقائية',
    pmSaved: 'تم حفظ الصيانة الوقائية بنجاح!',
    completePM: 'إكمال الصيانة الوقائية'
  }
};
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
export function LanguageProvider({
  children
}: {
  children: React.ReactNode;
}) {
  const [language, setLanguage] = useState<Language>('en');
  // Set initial direction on mount
  useEffect(() => {
    const dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language]);
  const toggleLanguage = () => {
    setLanguage(prev => {
      const newLang = prev === 'en' ? 'ar' : 'en';
      // Set direction based on new language
      const dir = newLang === 'ar' ? 'rtl' : 'ltr';
      document.documentElement.dir = dir;
      document.documentElement.lang = newLang;
      return newLang;
    });
  };
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };
  return <LanguageContext.Provider value={{
    language,
    toggleLanguage,
    t
  }}>
      {children}
    </LanguageContext.Provider>;
}
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}